name: CI/CD

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "16"
      - name: install packages
        run: yarn install
      - name: check linting
        run: yarn lint
      - name: build
        run: yarn build
      - name: deploy on github pages
        run: yarn deploy
